version: "2"

networks:
  default:
    external:
      name: jenkins


services:
  jenkins:
      container_name: jenkins
      image:  issc29/jenkins-docker:2.277.1-lts-alpine
      volumes:
          - ~/Documents/jenkins:/var/jenkins_home
      restart: always
      ports:
          - "9999:8080"
          - "50000:50000"
      environment:
          - DOCKER_HOST=tcp://docker-service:2375


  # https://hub.docker.com/r/verb/socat/
  # clever way to expose host docker engine to internal services
  docker-service:
   container_name: docker-service
   image: verb/socat:alpine
   command: tcp-listen:2375,reuseaddr,fork unix:/docker.sock
   expose:
     - "2375"
   volumes:
     - /var/run/docker.sock:/docker.sock
