jenkinsldap:
    container_name: ldap
    image: osixia/openldap:1.1.7
    volumes:
        - /data/ldap/database:/var/lib/ldap
        - /data/ldap/config:/etc/ldap/slapd.d
    restart: always
    ports:
          - "389:389"
jenkinsphpldap:
    container_name: phpldapadmin
    image: osixia/phpldapadmin:0.6.12
    ports:
        - "443:443"
    links:
        - ldap
    environment:
        - PHPLDAPADMIN_LDAP_HOSTS=ldap
    restart: always
